# Generated by Django 5.0.4 on 2024-04-15 23:51

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mushroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('common_name', models.CharField(blank=True, max_length=200)),
                ('latin_name', models.CharField(max_length=200)),
                ('image_url', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20)),
                ('e_name', models.CharField(max_length=100)),
                ('e_phone', models.CharField(max_length=20)),
                ('avatar', models.URLField(blank=True)),
                ('expiration_date', models.DateField()),
                ('role', models.CharField(default='member', max_length=50)),
                ('notes', models.TextField()),
                ('family', models.CharField(max_length=255)),
                ('skills', models.CharField(max_length=500)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('general_location', models.CharField(max_length=100)),
                ('specific_location', models.CharField(blank=True, max_length=200)),
                ('time_start', models.TimeField(default=datetime.time(9, 0))),
                ('time_end', models.TimeField(default=datetime.time(15, 0))),
                ('capacity', models.IntegerField(default=12)),
                ('restrictions', models.TextField(blank=True)),
                ('image_url', models.URLField(default='https://cdn.pixabay.com/photo/2023/10/21/11/23/ai-generated-8331261_1280.png')),
                ('note', models.TextField(blank=True)),
                ('status', models.CharField(verbose_name=100)),
                ('mushrooms', models.ManyToManyField(to='field_trips.mushroom')),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('registered', 'Registered'), ('chosen', 'Chosen'), ('waitlisted', 'Waitlisted'), ('rejected', 'Rejected')], default='registered', max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='field_trips.trip')),
            ],
        ),
    ]
