# Generated by Django 5.0.4 on 2024-04-17 19:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field_trips', '0004_remove_profile_role_alter_profile_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.URLField(default='https://cdn.pixabay.com/photo/2024/01/24/09/01/ai-generated-8529072_1280.png'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='expiration_date',
            field=models.DateField(default=datetime.datetime(2025, 4, 17, 19, 43, 0, 15512, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='family',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='notes',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='skills',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
