# Generated by Django 5.0.4 on 2024-04-17 22:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field_trips', '0005_alter_profile_avatar_alter_profile_expiration_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='expiration_date',
            field=models.DateField(default=datetime.datetime(2025, 4, 17, 22, 7, 29, 197364, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='trip',
            name='status',
            field=models.CharField(default='Registration Open', verbose_name=100),
        ),
    ]
