# Generated by Django 5.0.4 on 2024-04-17 22:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field_trips', '0008_alter_profile_expiration_date_alter_trip_mushrooms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='expiration_date',
            field=models.DateField(default=datetime.datetime(2025, 4, 17, 22, 50, 7, 893504, tzinfo=datetime.timezone.utc)),
        ),
    ]
