# Generated by Django 5.0.4 on 2024-04-17 23:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field_trips', '0009_alter_profile_expiration_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mushroom',
            options={'ordering': ['latin_name']},
        ),
        migrations.AlterField(
            model_name='profile',
            name='expiration_date',
            field=models.DateField(default=datetime.datetime(2025, 4, 17, 23, 0, 9, 984987, tzinfo=datetime.timezone.utc)),
        ),
    ]
