# Generated by Django 5.0.4 on 2024-04-18 17:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field_trips', '0010_alter_mushroom_options_alter_profile_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='expiration_date',
            field=models.DateField(default=datetime.datetime(2025, 4, 18, 17, 20, 50, 679754, tzinfo=datetime.timezone.utc)),
        ),
    ]
