# Generated by Django 5.0.4 on 2024-04-18 17:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field_trips', '0011_alter_profile_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='expiration_date',
            field=models.DateField(default=datetime.datetime(2025, 4, 18, 17, 21, 13, 494286, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='registration',
            name='status',
            field=models.CharField(choices=[('registered', 'Registered'), ('accepted', 'Accepted'), ('waitlisted', 'Waitlisted'), ('rejected', 'Rejected')], default='registered', max_length=10),
        ),
    ]
