# Generated by Django 5.0.4 on 2024-04-19 17:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field_trips', '0014_trip_waitlist_alter_profile_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='expiration_date',
            field=models.DateField(default=datetime.datetime(2025, 4, 19, 17, 22, 47, 58487, tzinfo=datetime.timezone.utc)),
        ),
    ]
