# Generated by Django 5.0.4 on 2024-04-24 16:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field_trips', '0015_alter_profile_expiration_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=250)),
                ('cost', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='expiration_date',
            field=models.DateField(default=datetime.datetime(2025, 4, 24, 16, 19, 7, 696113, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='trip',
            name='permits',
            field=models.ManyToManyField(blank=True, to='field_trips.permit'),
        ),
    ]
