# Generated by Django 5.0.4 on 2024-04-24 16:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field_trips', '0016_permit_alter_profile_expiration_date_trip_permits'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permit',
            name='cost',
        ),
        migrations.AddField(
            model_name='permit',
            name='annual_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='permit',
            name='day_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='profile',
            name='expiration_date',
            field=models.DateField(default=datetime.datetime(2025, 4, 24, 16, 34, 2, 884496, tzinfo=datetime.timezone.utc)),
        ),
    ]
