# Generated by Django 5.0.4 on 2024-04-24 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('field_trips', '0017_remove_permit_cost_permit_annual_cost_and_more'),
    ]

    operations = [
    ]
