# Generated by Django 5.0.4 on 2024-04-30 15:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field_trips', '0019_alter_profile_expiration_date_alter_profile_family_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='expiration_date',
            field=models.DateField(default=datetime.datetime(2025, 4, 30, 15, 54, 52, 445983, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='trip',
            name='specific_location',
            field=models.CharField(blank=True, default='45.3420633, -121.9420244', max_length=200),
        ),
    ]
