# Generated by Django 5.0.4 on 2024-05-03 04:08

import field_trips.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field_trips', '0020_alter_profile_expiration_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='expiration_date',
            field=models.DateField(default=field_trips.models.one_year_from_now),
        ),
    ]
